const theme = {
  fontSource: "https://fonts.googleapis.com/css?family=Poppins:400,600",
  fontFamily: "Poppins, sans-serif",
  color: {
    modaDarkGreen: "#2A9D8F",
    modaLightGreen: "#94D2BD",
    modaPurple: "#6A53F2",
    modaLightPurple: "#F0E8F5",
    modaYelloGreen: "#D4E364",
    modaLightYellow: "#686765",
    modaBlack: "#263238",
    background: "#708B75",
    error: "#da1e28",
    backgroundgrey: "#E5E5E5",
    link: "#9AB87A",
  },
  font: {
    size: {
      extraSmall: "14px",
      small: "16px",
      medium: "18px",
      large: "20px",
      extraLarge: "24px",
    },
    family: "sans-serif",
  },
  breakpoint: {
    mobile: "375px",
    tablet: "600px",
    laptop: "1200px",
    desktop: "1600px",
  },
  buttons: {
    colored: {
      display: "block",
      "margin-top": "1rem",
      width: "40%",
      border: "none",
      padding: "15px 20px",
      "background-color": "#2A9D8F",
      color: "white",
      cursor: "pointer",
    },
    light: {
      padding: "10px",
      border: "2px solid black",
      fontSize: "20px",
      "background-color": "white",
      cursor: "pointer",
    },
    dark: {},
    grey: {
      padding: "15px",
      border: "0px",
      fontSize: "2rem",
      color: "gray",
    },
  },
};
export default theme;
